import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Synapse OS Design Tokens
        "on-secondary": "#313030",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#656464",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        secondary: "#c9c6c5",
        "on-tertiary-fixed": "#1c1b1b",
        primary: "#ffffff",
        "surface-container-low": "#1c1b1b",
        error: "#ffb4ab",
        "secondary-fixed-dim": "#c9c6c5",
        "on-background": "#e5e2e1",
        "tertiary-fixed": "#e5e2e1",
        "on-primary-fixed": "#1a1c1c",
        "on-error": "#690005",
        surface: "#141313",
        "secondary-container": "#4a4949",
        "on-tertiary-fixed-variant": "#474746",
        "primary-fixed-dim": "#c6c6c7",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed-variant": "#474646",
        "primary-fixed": "#e2e2e2",
        "on-primary-container": "#636565",
        "inverse-primary": "#5d5f5f",
        "surface-tint": "#c6c6c7",
        "on-surface": "#e5e2e1",
        "on-primary-fixed-variant": "#454747",
        "on-primary": "#2f3131",
        "surface-variant": "#353434",
        "primary-container": "#e2e2e2",
        "on-surface-variant": "#c4c7c8",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        tertiary: "#ffffff",
        "surface-container": "#201f1f",
        outline: "#8e9192",
        background: "#141313",
        "on-secondary-container": "#bab8b7",
        "outline-variant": "#444748",
        "surface-dim": "#141313",
        "error-container": "#93000a",
        "surface-container-highest": "#353434",
        "tertiary-container": "#e5e2e1",
        "surface-bright": "#3a3939",
        "on-tertiary": "#313030",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "panel-context": "320px",
        gutter: "16px",
        "panel-nav": "240px",
        "container-padding": "24px",
        "stack-gap": "8px",
      },
      fontFamily: {
        "mono-label": ["Geist Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
      },
      fontSize: {
        "mono-label": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
